A/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('saloons.urls', namespace='saloons')),
    path('contact/', include('contacts.urls', namespace='contacts')),
    path('reserve/', include('reservation.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('api-auth', include('rest_framework.urls')),
    path('api/token/', TokenObtainPairView.as_view()),
    path('api/token/refresh', TokenRefreshView.as_view()),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

saloons/api/urls.py
from django.urls import path
from . import views


app_name = 'saloons'

urlpatterns = [
	path('saloon/<slug:slug>/', views.api_get_saloon_detail, name='api_saloon_detail'),
	path('saloon/<slug:slug>/update/', views.api_change_saloon_detail, name='api_saloon_update'),
	path('saloon/<slug:slug>/delete/', views.api_delete_saloon_detail, name='api_saloon_delete'),
	path('saloon/create/', views.api_create_saloon_view, name='api_saloon_create'),
	path('saloon/list', views.APISaloonListView.as_view(), name='api_saloon_list'),
]

saloons/urls.py
from django.urls import path, include
from . import views


app_name = 'saloons'

urlpatterns = [
	path('api/v1/', include('saloons.api.urls', namespace='saloons')),
	path('', views.saloon_list, name='saloons_list'),
	path('<slug:slug>/', views.saloon_detail, name='saloons_detail'),
	path('city/<str:slug>/', views.saloon_city, name='saloons_city'),
	# path('search-city/', views.search_city, name='search_city'),
	path('province/<str:slug>/', views.saloon_province, name='saloons_province'),
	path('payment/<int:reserve_id>/<int:amount>/', views.payment, name='payment'),
	path('payment/verify/', views.verify, name='verify'),
]

saloons/forms.py
from django import forms
from jalali_date.fields import JalaliDateField
from jalali_date.widgets import AdminJalaliDateWidget


class ReserveDatetime(forms.Form):
	datetime = JalaliDateField(label='انتخاب تاریخ',
	                           widget=AdminJalaliDateWidget)
	hour = forms.IntegerField(max_value=24, min_value=1,
	                            label='انتخاب ساعت')



class SelectTypeForm(forms.Form):
	TYPE = (
		('su', 'چمن'),
		('sa', 'سالن'),
	)
	type = forms.ChoiceField(choices=TYPE,
	                         label='انتخاب نوع')


class SelectGenderForm(forms.Form):
	GENDER = (
		('b', 'بانوان و آقایان'),
		('m', 'آقایان'),
		('f', 'بانوان'),
	)
	gender = forms.ChoiceField(choices=GENDER,
	                           label='انتخاب جنسیت')


class SearchSaloonForm(forms.Form):
	search_text = forms.CharField(label='جستجو شهر',
	                         widget=forms.TextInput({
		                         'placeholder': 'نام شهر خود را بنویسید ...',
                                 'id': 'search_city'}))

saloons/api/views.py
from rest_framework import viewsets, permissions, status
from rest_framework.response import Response
from rest_framework.decorators import api_view, permission_classes
from .serializer import SaloonSerializer
from ..models import Saloon
from accounts.models import User
from rest_framework.pagination import PageNumberPagination
from rest_framework.generics import ListAPIView
from rest_framework.authentication import TokenAuthentication
from rest_framework.filters import SearchFilter, OrderingFilter
# class SaloonView(viewsets.ModelViewSet):
# 	queryset = Saloon.active_saloons.all()
# 	serializer_class = SaloonSerializer
# 	permission_classes = permissions.IsAuthenticatedOrReadOnly


@api_view(['GET'])
@permission_classes((permissions.IsAuthenticated, ))
def api_get_saloon_detail(request, slug):
	try:
		get_saloon = Saloon.objects.get(slug=slug)
	except Saloon.DoesNotExist:
		return Response(status=status.HTTP_404_NOT_FOUND)

	if request.method == 'GET':
		serializer = SaloonSerializer(get_saloon)
		return Response(serializer.data)


@api_view(['PUT'])
@permission_classes((permissions.IsAuthenticated, ))
def api_change_saloon_detail(request, slug):
	try:
		get_saloon = Saloon.objects.get(slug=slug)
	except Saloon.DoesNotExist:
		return Response(status=status.HTTP_404_NOT_FOUND)

	user = request.user
	if get_saloon.owner != user:
		return Response(data={'status': "You done permission to edit"})

	if request.method == 'PUT':
		serializer = SaloonSerializer(get_saloon, data=request.data)
		data = {}
		if serializer.is_valid():
			serializer.save()
			data['status'] = True
			return Response(data=data)
		return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)



@api_view(['DELETE'])
@permission_classes((permissions.IsAuthenticated, ))
def api_delete_saloon_detail(request, slug):
	try:
		get_saloon = Saloon.objects.get(slug=slug)
	except Saloon.DoesNotExist:
		return Response(status=status.HTTP_404_NOT_FOUND)

	user = request.user
	if get_saloon.owner != user:
		return Response(data={'status': "You done permission to delete"})

	if request.method == 'DELETE':
		operation = get_saloon.delete()
		data = {}
		if operation:
			data['status'] = True
		else:
			data['status'] = False
		return Response(data=data)



@api_view(['POST'])
@permission_classes((permissions.IsAuthenticated, ))
def api_create_saloon_view(request):
	account = request.user
	create_saloon = Saloon(owner=account)

	if request.method == 'POST':
		serializer = SaloonSerializer(create_saloon, data=request.data)
		if serializer.is_valid():
			serializer.save()
			return Response(serializer.data, status=status.HTTP_201_CREATED)
		return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class APISaloonListView(ListAPIView):
	queryset = Saloon.active_saloons.all()
	authentication_classes = (TokenAuthentication, )
	permission_classes = (permissions.IsAuthenticated, )
	serializer_class = SaloonSerializer
	pagination_class = PageNumberPagination
	filter_backends = (SearchFilter, OrderingFilter)
	search_feilds = ('title', 'city', 'province')

saloons/views.py
from django.shortcuts import render, get_object_or_404, redirect, get_list_or_404
from django.http import HttpResponse
from django.views import generic
from .models import Saloon, Image
from reservation.models import Reservation
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from .forms import ReserveDatetime, SelectTypeForm, SelectGenderForm, SearchSaloonForm
from django.contrib import messages
from khayyam import *
from datetime import datetime, date
from suds import Client
from payments.models import Payment
from django.core.cache import cache
from django.views.decorators.cache import cache_page


@cache_page(60 * 20)
def saloon_list(request):
	cache_time = 60 * 20
	cache_key = 'cache_key2'
	saloons_list = cache.get(cache_key)
	if not saloons_list:
		saloons_list = Saloon.active_saloons.all()

	cache.set(cache_key, saloons_list, cache_time)
	type_form = SelectTypeForm()
	gender_form = SelectGenderForm()
	search_form = SearchSaloonForm()

	if request.method == 'GET':
		type = request.GET.get('type')
		gender = request.GET.get('gender')

		if type is not None and gender is not None:
			saloons_list = Saloon.active_saloons.filter(type=type,
			                                            gender=gender)

	if request.method == 'GET':
		search_text = request.GET.get('search_text')
		if search_text is not None and search_text != u"":
			search_text = request.GET.get('search_text')
			saloons_list = Saloon.active_saloons.filter(city__contains=search_text)


	context = {
		'saloons_list': saloons_list,
		'type_form':  type_form,
		'gender_form':  gender_form,
		'search_form': search_form
	}
	return render(request, 'saloons/saloons_list.html', context)


# def search_city(request):
#
#
# 		return render(request, 'saloons/saloons_list.html', {'saloons_list': city})

@cache_page(60 * 20)
def saloon_detail(request, slug):
	cache_key = f'saloon-{slug}'
	images_cache_key = f'images-{cache_key}'
	get_saloon = cache.get(cache_key)
	images = cache.get(images_cache_key)
	if not get_saloon or not images:
		get_saloon = get_object_or_404(Saloon, slug=slug)
		images = Image.objects.filter(saloon=get_saloon)

	cache.set(cache_key, get_saloon, 60 * 20)
	cache.set(images_cache_key, images, 60 * 20)

	if request.method == 'POST':
		if request.user.is_authenticated:
			form = ReserveDatetime(request.POST)
			if form.is_valid():
				reserved_date = form.cleaned_data['datetime']
				hour = form.cleaned_data['hour']
				make_str = f'{reserved_date}'
				# Save to database
				make_datetime = datetime.strptime(make_str, '%Y-%m-%d')
				# print('$'*51, make_datetime)
				# Show to user
				make_jalali = JalaliDate(make_datetime).strftime('%Y-%m-%d')
				# print('='*51, make_jalali)
				if make_datetime < datetime.strptime(datetime.now().strftime('%Y-%m-%d'), '%Y-%m-%d'):
					messages.error(request, 'تاریخ انتخاب شده شما گذشته است', 'warning')
					return redirect('saloons:saloons_detail', slug)
				if hour not in range(get_saloon.start_time, get_saloon.end_time):
					messages.error(request, 'سانس انتخاب شده شما خارج از محدوده فعالیت {} می‌باشد!'
					               .format(get_saloon.name), 'warning')
					return redirect('saloons:saloons_detail', slug)
				create_reserve = Reservation.objects.filter(reserve_date__exact=make_datetime,
				                                            saloon=get_saloon,
				                                            hour=hour,
				                                            status='r').exists()
				if create_reserve:
					messages.error(request, 'سانس مد نظر شما رزرو شده است، ساعت و'
					                        ' یا تاریخ دیگری را انتخاب نمایید', 'warning')
				else:
					reserve = Reservation.objects.create(user=request.user,
					                                     saloon=get_saloon,
					                                     reserve_date=make_datetime,
					                                     hour=hour)
					reserve.save()
					messages.success(request, 'با موفقیت سانس خود را موقتا انتخاب کردید.', 'success')
					return redirect('saloons:payment', reserve.id, get_saloon.amount)
			else:
				print('not valid')
		else:
			messages.success(request, 'برای ثبت رزرو لطفا وارد حساب خود شوید', 'warning')
			return redirect('accounts:user_login')
	else:
		form = ReserveDatetime()
	context = {
		'saloon': get_saloon,
		'images': images,
		'form': form
	}
	return render(request, 'saloons/saloon_detail.html', context)


MERCHANT = 'XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX'
client = Client('https://sandbox.zarinpal.com/pg/services/WebGate/wsdl')
description = "توضیحات پرداخت"
mobile = '09123456789'
amount = None
CallbackURL = 'http://localhost:8000/payment/verify/'


@login_required
def payment(request, reserve_id, amount):
	request.session[f'{request.user}'] = {
		'user': {
			'reserve_id': reserve_id,
			'amount': amount + 1000
		},
	}
	result = client.service.PaymentRequest(
			MERCHANT, amount + 1000, description, request.user.email, mobile, CallbackURL)
	if result.Status == 100:
		return redirect('https://sandbox.zarinpal.com/pg/StartPay/' + str(result.Authority))
	else:
		return HttpResponse('Error code: ' + str(result.Status))


@login_required
def verify(request):
	if request.GET.get('Status') == 'OK':
		result = client.service.PaymentVerification(
				MERCHANT, request.GET['Authority'], request.session[f'{request.user}'].get('user')['amount'])
		if result.Status == 100:
			try:
				reserve_id = request.session[f'{request.user}'].get('user')['reserve_id']
				reserve = Reservation.objects.get(id=reserve_id)
				reserve.status = 'r'
				reserve.save()
				Payment.objects.create(reserve=reserve,
				                       authority=request.GET['Authority'],
				                       refid=0,
				                       status=result.Status,
				                       paid=True)
				messages.success(request, 'رزرو سالن با موفقیت انجام شد', 'success')
				del request.session[f'{request.user}']
				return redirect('accounts:user_index')
			except Reservation.DoesNotExist:
				messages.success(request, 'رزرو نامعتبر', 'danger')
				return redirect('saloons:saloons_list')


		elif result.Status == 101:
			return HttpResponse('Transaction submitted')
		else:
			return HttpResponse('Transaction failed')
	else:
		try:
			reserve_id = request.session[f'{request.user}'].get('user')['reserve_id']
			reserve = Reservation.objects.get(id=reserve_id)
			Payment.objects.create(reserve=reserve,
			                       authority=request.GET['Authority'],
			                       refid=0,
			                       status=200,
			                       paid=False)
			del request.session[f'{request.user}']
			messages.success(request, 'عملیات پرداخت کنسل شد', 'danger')
			return redirect('saloons:saloons_list')
		except Reservation.DoesNotExist:
			messages.success(request, 'رزرو نامعتبر', 'danger')
			return redirect('saloons:saloons_list')



def saloon_city(request, slug):
	saloons = get_list_or_404(Saloon, city=slug)

	context = {
		'saloons_list': saloons
	}
	return render(request, 'saloons/saloon_filter.html', context)


def saloon_province(request, slug):
	saloons = get_list_or_404(Saloon, province=slug)

	context = {
		'saloons_list': saloons
	}
	return render(request, 'saloons/saloon_filter.html', context)

saloons/templates/saloons/saloon_detail.html
{% extends 'base.html' %}
{% load jalali_tags %}
{% load thumbnail %}
{% block head %}

<script src='https://api.mapbox.com/mapbox-gl-js/v1.11.1/mapbox-gl.js'></script>
<link href='https://api.mapbox.com/mapbox-gl-js/v1.11.1/mapbox-gl.css' rel='stylesheet' />

{% endblock %}

{% block title %}
{{ saloon.name }}
{% endblock %}

{% block content %}
<div class="container">

	<h4 class="text-center mt-5">تصاویری از محیط {% if saloon.type == 'su' %}چمن  {% else %} سالن {% endif %}</h4>
	<div class="col-10 mx-auto mt-5">
		<div id="demo" class="carousel slide" data-ride="carousel">

	  <!-- Indicators -->
	  <ul class="carousel-indicators">
	    {% for image in images %}
	        <li data-target="#demo" data-slide-to="{{ forloop.counter0 }}" class="{% if forloop.first %} active {% endif %}"></li>
	    {% endfor %}

	  </ul>

	  <!-- The slideshow -->
	  <div class="carousel-inner">
	    {% for image in images %}
	        <div class="carousel-item {% if forloop.first %} active {% endif %}">
	        <img src="{% thumbnail image.picture 800x400 crop %}" class="img-thumbnail" alt="{{ saloon.name }}">
	        </div>
	    {% endfor %}

	  </div>

	  <!-- Left and right controls -->
	  <a class="carousel-control-prev" href="#demo" data-slide="prev">
	    <span class="carousel-control-prev-icon"></span>
	  </a>
	  <a class="carousel-control-next" href="#demo" data-slide="next">
	    <span class="carousel-control-next-icon"></span>
	  </a>

	</div>
	</div>
	<div class="col-10 mx-auto">
		<div class="card mt-4">
			<div class="card-header">
				<div class="row">
					<div class="col-md-10">
						<h4 class="text-center">{{ saloon.name }}</h4>
					</div>
					<div class="col-md-2">
						<button  data-toggle="modal" data-target="#owner" class="btn btn-sm btn-outline-info text-center">
											{{ saloon.owner.first_name }}
											{{ saloon.owner.last_name }}
										</button>
										<div class="modal fade" id="owner" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
										  <div class="modal-dialog modal-dialog-centered" role="document">
										    <div class="modal-content">
										      <div class="modal-header">
										        <h5 class="modal-title" id="exampleModalLongTitle">درباره {{ saloon.owner.first_name }}
											{{ saloon.owner.last_name }}</h5>

										      </div>
										      <div class="modal-body">
												<ul>
													<img style="width: 50%; height: 50%;" class="img-thumbnail" src="{% thumbnail saloon.owner.user_profile.avatar 250x200 crop %}" alt="">
													<li>شماره تماس: {{ saloon.owner.phone }}</li>
													<li> پست الکترونیکی: {{ saloon.owner.email }}</li>
												</ul>
										      </div>
										      <div class="modal-footer">
										        <button type="button" class="btn btn-secondary" data-dismiss="modal">بستن</button>
										      </div>
										    </div>
										  </div>
									</div>
									</div>
				</div>
			</div>
			<div class="card-body">
				<div class="row">
					<div class="col-md-4 mt-2">
						ساعت کار {% if saloon.type == 'su' %}
						چمن
						{% else %}
						سالن
						{% endif %}  از
						{{ saloon.start_time }}
						تا
						{{ saloon.end_time }}
						می‌باشد.
					</div>
					<div class="col-md-4">
						استان:
						<a href="{% url 'saloons:saloons_province' saloon.province %}" class="btn btn-outline-primary">{{ saloon.province }}</a>
					</div>
					<div class="col-md-4">
						شهر:
						<a href="{% url 'saloons:saloons_city' saloon.city %}" class="btn btn-outline-danger">{{ saloon.city }}</a>
					</div>
				</div>
				<hr>
			<div class="row">
				<div class="col-md-4">
					<img class="img-thumbnail" src="{% thumbnail saloon.picture 250x200 crop %}" alt="{{ saloon.name }}" />
				</div>
				<div class="col-md-8">
					<div>
						{{ saloon.about|safe }}
					</div>
					<hr>
					<div class="text-center">
						<h5>امکانات </h5>
					</div>
					<div>
						<div class="row">
							{% for foo in saloon.features.all %}
								<div class="col-3">
									<li>{{ foo }}</li>
								</div>
							{% endfor %}
						</div>
					</div>
					<hr>
				<div class="row mx-auto">
					<h5 class="text-center mx-auto">روی نقشه</h5>
					<div class="col-12 img-thumbnail mx-auto" style="padding: 100px; " id="map"></div>
					<script>
						// TO MAKE THE MAP APPEAR YOU MUST
						// ADD YOUR ACCESS TOKEN FROM
						// https://account.mapbox.com
					mapboxgl.accessToken = 'pk.eyJ1IjoibGluaW9sb24iLCJhIjoiY2pzYWtrNTQzMDE1NTQ5bzZnN2hyMThyaiJ9.CUVl1SVPGqheh8sx0TQ61g';
					var map = new mapboxgl.Map({
					container: 'map',
					style: 'mapbox://styles/mapbox/streets-v11',
					center: [{{ saloon.on_map }}],
					zoom: 8
					});

					var marker = new mapboxgl.Marker()
					.setLngLat([{{ saloon.on_map }}])
					.addTo(map);
					</script>
				</div>
				</div>
			</div>
			</div>
			<div class="card-footer">

				<!-- Button trigger modal -->
				<button type="button" class="btn btn-success btn-block" data-toggle="modal" data-target="#exampleModalCenter">
					انتخاب سالن و رزرو
				</button>

				<!-- Modal -->
				<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
				  <div class="modal-dialog modal-dialog-centered" role="document">
				    <div class="modal-content">
				      <div class="modal-header">
				        <h5 class="modal-title" id="exampleModalLongTitle">انتخاب تاریخ و زمان</h5>

				      </div>
				      <div class="modal-body">
				        <form action="" method="post">
							{% csrf_token %}
							<div class="col-8 mx-auto">
								{{ form.as_p }}
								<input type="submit" class="btn btn-primary btn-block" value="چک کردن و ثبت رزرو">
							</div>
						</form>
				      </div>
				      <div class="modal-footer">
				        <button type="button" class="btn btn-secondary" data-dismiss="modal">بستن</button>
				      </div>
				    </div>
				  </div>
				</div>

			</div>
			</div>
		</div>
	</div>
{% endblock %}

saloons/templates/saloons/saloon_filter.html
{% extends 'base.html' %}

{% block title %}
	خانه
{% endblock %}

{% block content %}
	<div class="container">
		<div class="text-center mt-5">
			<h3>لیست سالن‌ها و چمن‌ها</h3>
		</div>
		<div class="row"  style="display: block;">
			<div class="col-10 mx-auto">
					{% for saloon in saloons_list %}
						<div class="card mt-4">
							<div class="card-header">
								<div class="row">
									<div class="col-md-10 mx-auto">
										<h4 class="text-center">{{ saloon.name }}</h4>
									</div>

								</div>
							</div>
							<div class="card-body">
								<div class="row">
									<div class="col-md-4 mt-2">
										ساعت کار {% if saloon.type == 'su' %}
										چمن
										{% else %}
										سالن
										{% endif %}  از
										{{ saloon.start_time }}
										تا
										{{ saloon.end_time }}
										می‌باشد.
									</div>
									<div class="col-md-4">
										استان:
										<a href="{% url 'saloons:saloons_province' saloon.province %}" class="btn btn-outline-primary">{{ saloon.province }}</a>
									</div>
									<div class="col-md-4">
										شهر:
										<a href="{% url 'saloons:saloons_city' saloon.city %}" class="btn btn-outline-danger">{{ saloon.city }}</a>
									</div>
								</div>
								<hr>
							<div class="row">
								<div class="col-md-4">
									<img class="img-thumbnail" src="{{ saloon.picture.url }}" alt="{{ saloon.name }}" />
								</div>
								<div class="col-md-8">
									<div>
										{{ saloon.about|safe|truncatewords:100 }}
									</div>
								</div>
							</div>
							</div>
							<div class="card-footer">
								<a href="{{ saloon.get_absoulte_url }}" class="btn btn-block btn-success">انتخاب سالن و رزرو</a>
							</div>
						</div>
					{% endfor %}
			</div>

		</div>
	</div>
{% endblock %}

saloons/templates/saloons/saloons_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load cache %}
{% load static %}
{% load thumbnail %}


{% block title %}
	خانه
{% endblock %}

{#{% cache 500 content %}#}
{% block content %}
	<div class="container-fluid"  id="result">
	<div class="row">

{#		Start Column#}
			<div class="col-4 mt-1">
			<div class="text-center mt-5 mx-auto">
				<h4>فیلتر کردن</h4>
			</div>
				<div class="card mt-3">
					<div class="card-body">
						<div class="card">
							<div class="card-header">
								<h5>فیلتر براساس</h5>
							</div>
							<div class="card-body">
								<form action="" method="get">
									{% csrf_token %}
									{{ type_form.type|as_crispy_field }}
									{{ gender_form.gender|as_crispy_field }}
									<input type="submit" class="btn btn-primary" value="اعمال فیلتر">
									<a href="{% url 'saloons:saloons_list' %}" class="btn btn-danger">حذف فیلتر</a>
								</form>
								<hr>
								<form action="" method="get">
									{% csrf_token %}
									{{ search_form|crispy }}
								</form>
							</div>
						</div>

					</div>
				</div>
			</div>

			<div class="col-8 ">
			<div class="text-center mt-5 mx-auto">
			<h3>لیست سالن‌ها و چمن‌ها</h3>

					{% for saloon in saloons_list %}
						<div class="card mt-4">
							<div class="card-header">
								<div class="row">
									<div class="col-md-10 mx-auto">
										<h4 class="text-center">{{ saloon.name }}</h4>
									</div>

								</div>
							</div>
							<div class="card-body">
								<div class="row">
									<div class="col-md-4 mt-2">
										ساعت کار {% if saloon.type == 'su' %}
										چمن
										{% else %}
										سالن
										{% endif %}  از
										{{ saloon.start_time }}
										تا
										{{ saloon.end_time }}
										می‌باشد.
									</div>
									<div class="col-md-4">
										استان:
										<a href="{% url 'saloons:saloons_province' saloon.province %}" class="btn btn-outline-primary">{{ saloon.province }}</a>
									</div>
									<div class="col-md-4">
										شهر:
										<a href="{% url 'saloons:saloons_city' saloon.city %}" class="btn btn-outline-danger">{{ saloon.city }}</a>
									</div>
								</div>
								<hr>
							<div class="row">
								<div class="col-md-4">
									<img class="img-thumbnail" src="{% thumbnail saloon.picture 250x200 crop %}" alt="{{ saloon.name }}" />
								</div>
								<div class="col-md-8">
									<div>
										{{ saloon.about|safe|truncatewords:100 }}
									</div>
								</div>
							</div>
							</div>
							<div class="card-footer">
								<a href="{{ saloon.get_absoulte_url }}" class="btn btn-block btn-success">انتخاب سالن و رزرو</a>
							</div>
						</div>
					{% endfor %}

			</div>


		</div>
	</div>
	</div>

{% endblock %}
{#{% endcache %}#}