A/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('saloons.urls', namespace='saloons')),
    path('contact/', include('contacts.urls', namespace='contacts')),
    path('reserve/', include('reservation.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('api-auth', include('rest_framework.urls')),
    path('api/token/', TokenObtainPairView.as_view()),
    path('api/token/refresh', TokenRefreshView.as_view()),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path, include
from . import views


app_name = 'accounts'

urlpatterns = [
    path('', views.user_index, name='user_index'),
    path('api/v1/', include('accounts.api.urls', namespace='accounts')),
    path('manager/', views.user_manager, name='user_manager'),
    path('register/', views.user_register, name='user_register'),
    path('login/', views.user_login, name='user_login'),
    path('active/', views.user_active, name='user_active'),
    path('verify/<str:email>/<str:code>/', views.user_verify, name='user_verify'),
    path('resend/', views.resend_code, name='resend_code'),
    path('forget/', views.user_forget, name='user_forget'),
    path('change-password/', views.user_change_password, name='user_change_password_reset'),
    path('change-password/<str:email>/<str:code>/', views.user_change_password, name='user_change_password'),
    path('logout/', views.user_logout, name='user_logout'),
]

contacts/urls.py
from django.urls import path
from . import views

app_name = 'contacts'


urlpatterns = [
	path('us/', views.contact, name='contact'),
	path('about-us/', views.about, name='about'),
]

saloons/urls.py
from django.urls import path, include
from . import views


app_name = 'saloons'

urlpatterns = [
	path('api/v1/', include('saloons.api.urls', namespace='saloons')),
	path('', views.saloon_list, name='saloons_list'),
	path('<slug:slug>/', views.saloon_detail, name='saloons_detail'),
	path('city/<str:slug>/', views.saloon_city, name='saloons_city'),
	# path('search-city/', views.search_city, name='search_city'),
	path('province/<str:slug>/', views.saloon_province, name='saloons_province'),
	path('payment/<int:reserve_id>/<int:amount>/', views.payment, name='payment'),
	path('payment/verify/', views.verify, name='verify'),
]

templates/inc/footer.html
<!-- Footer -->
<footer class="page-footer text-right bg-light text-dark mt-5" style="direction: rtl;">
 
    <!-- Footer Links -->
    <div class="container text-center text-md-left">

        <!-- Grid row -->
        <div class="row">

            <!-- Grid column -->
            <div class="col-md-4 col-lg-3 mr-auto my-md-4 my-0 mt-4 mb-1">

                <!-- Content -->
                <h5 class="font-weight-bold text-uppercase mb-4">توضیحات</h5>

            </div>
            
            <hr class="clearfix w-100 d-md-none">

            <!-- Grid column -->
            <div class="col-md-4 col-lg-3 mx-auto my-md-4 my-0 mt-4 mb-1">

                <!-- Contact details -->
                <h5 class="font-weight-bold text-uppercase mb-4">آدرس</h5>

                <ul class="list-unstyled">
                    <li>
                        بوشهر - برازجان
                    </li>
                    <li>
                        amirkouhkan[at]gmail.com
                    </li>
                </ul>

            </div>
           

        </div>
        <!-- Grid row -->

    </div>
    <!-- Footer Links -->

    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">حقوق مادی و معنوی این وب‌سایت محفوظ می‌باشد. ۱۳۹۹
        <a href="https://liniolon.blog.ir" class="btn btn-outline-info" target="_blank"> وبلاگ امیر کوهکن</a>
    </div>
    <!-- Copyright -->

</footer>
<!-- Footer -->

templates/inc/messages.html
{% if messages %}
  {% for message in messages %}
    <p class="mt-3 alert alert-{{message.tags}}">{{message}}</p>
  {% endfor %}
{% endif %}

templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light p-4">
    <a class="nav-link" href="{% url 'saloons:saloons_list' %}">سالن‌ها</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'saloons:saloons_list' %}">سالن‌ها</a>
            </li>
        <li class="nav-item">
	         <a class="nav-link" href="{% url 'contacts:contact' %}">تماس با ما</a>
        </li>
         <li class="nav-item">
	         <a class="nav-link" href="{% url 'contacts:about' %}">درباره ما</a>
        </li>
            
            <!-- Dropdown -->
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown">
                    ناحیه کاربری
                </a>
                <div class="dropdown-menu" >
                    
                    {% if request.user.is_authenticated %}
                    <a class="dropdown-item" href="{% url 'accounts:user_index' %}">خانه</a>
	                    {% if request.user.is_staff %}
                        <a class="dropdown-item" href="{% url 'accounts:user_manager' %}">بخش مدیریت</a>
	                    {% endif %}
                    <a class="dropdown-item" href="{% url 'accounts:user_logout' %}">خروج</a>
                    {% else %}
                    <a class="dropdown-item" href="{% url 'accounts:user_login' %}">ورود</a>
                    <a class="dropdown-item" href="{% url 'accounts:user_register' %}">ثبت نام</a>
                    {% endif %}
                        
                </div>
            </li>
        </ul>
    </div>
</nav>